#ifndef __PLUG_IN_HEADER__
#define __PLUG_IN_HEADER__

// plugin

#define PLUGIN_INI_FUNC_DEFAAULT_NAME Ini
#define PLUGIN_QUIT_FUNC_DEFAAULT_NAME Quit
#define PLUGIN_RUN_FUNC_DEFAAULT_NAME Run
#define PLUGIN_INPUT_FUNC_DEFAAULT_NAME Input
#define PLUGIN_GET_FUNC_DEFAAULT_NAME Get
#define PLUGIN_SET_FUNC_DEFAAULT_NAME Set

#define PLUGIN_INI_FUNC_DEFAAULT_NAME_STR	L"Ini"
#define PLUGIN_QUIT_FUNC_DEFAAULT_NAME_STR	L"Quit"
#define PLUGIN_RUN_FUNC_DEFAAULT_NAME_STR	L"Run"
#define PLUGIN_INPUT_FUNC_DEFAAULT_NAME_STR	L"Input"
#define PLUGIN_GET_FUNC_DEFAAULT_NAME_STR	L"Get"
#define PLUGIN_SET_FUNC_DEFAAULT_NAME_STR	L"Set"

#define PLUGIN_MAX_FUNC_NAME_LENGTH 256

// config

#define PLUGIN_CONTAINER_SEP_STR L"; "

#define PLUGIN_CONTAINER_CONFIG_FILE_LIST_KEY L"modules"
#define PLUGIN_CONTAINER_CONFIG_NAME_LIST_KEY L"module_names"

#define PLUGIN_HANDLE_INPUT_STATUS bool
#define PLUGIN_HANDLE_INPUT_END true
#define PLUGIN_HANDLE_INPUT_CONTINUE false

#endif
