#ifndef __PLUG_HEADER__
#define __PLUG_HEADER__

#define PLUGIN_INI_FUNC_DEFAAULT_NAME L"Ini"
#define PLUGIN_RUN_FUNC_DEFAAULT_NAME L"Run"
#define PLUGIN_INPUT_FUNC_DEFAAULT_NAME L"Input"

#define PLUGIN_CONTAINER_SEP_STR L"; "

#define PLUGIN_CONTAINER_CONFIG_FILE_LIST_KEY L"modules"
#define PLUGIN_CONTAINER_CONFIG_NAME_LIST_KEY L"module_names"

#endif
